apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-slave-config
data:
  my.cnf: |
    [mysqld]
    server-id=__SERVER_ID__
    log_bin=mysql-bin
    gtid_mode=ON
    enforce_gtid_consistency=ON
    relay_log=mysql-relay-bin
    read_only=ON
    bind-address=0.0.0.0
    ssl-ca=/etc/mysql/ssl/ca-cert.pem
    ssl-cert=/etc/mysql/ssl/server-cert.pem
    ssl-key=/etc/mysql/ssl/server-key.pem
    report-host=__REPORT_HOST__  # Dynamically set this for each replica, its used for PMA
